// FUL-35a: WASM Core Integration - TypeScript bindings
// Provides a clean TypeScript interface to the Rust WASM simulation

import { Material, MATERIAL_NAMES } from './materials';

// WASM Module interface (generated by wasm-bindgen)
export interface WasmSimulation {
  new(width: number, height: number): WasmSimulation;
  tick(): void;
  tick_many(count: number): void;
  spawn(x: number, y: number, material: string): boolean;
  spawn_brush(cx: number, cy: number, material: string, radius: number): number;
  get_material(x: number, y: number): string;
  get_lifetime(x: number, y: number): number;
  particle_count(): number;
  width(): number;
  height(): number;
  clear(): void;
  render_rgba(): Uint8Array;
  render_rgba_direct(): void;
  take_pixel_buffer(): Uint8Array;
}

// Global WASM module state
let wasmModule: typeof import('./pkg/falling_sand') | null = null;
let wasmInitPromise: Promise<void> | null = null;

/**
 * Initialize the WASM module
 * Must be called before using any WASM simulation
 */
export async function initWasm(): Promise<void> {
  if (wasmModule) return; // Already initialized
  
  if (wasmInitPromise) {
    await wasmInitPromise;
    return;
  }
  
  wasmInitPromise = (async () => {
    try {
      // Dynamic import of WASM package (generated by wasm-pack)
      const wasm = await import('./pkg/falling_sand.js');
      await wasm.default();
      wasmModule = wasm;
      console.log('WASM simulation module initialized');
    } catch (error) {
      console.warn('WASM initialization failed, falling back to JS simulation:', error);
      wasmModule = null;
    }
  })();
  
  await wasmInitPromise;
}

/**
 * Check if WASM is available and initialized
 */
export function isWasmAvailable(): boolean {
  return wasmModule !== null;
}

/**
 * Create a new WASM simulation
 */
export function createWasmSimulation(width: number, height: number): WasmSimulation | null {
  if (!wasmModule) {
    console.warn('WASM not available, use JS simulation');
    return null;
  }
  
  try {
    return new wasmModule.Simulation(width, height);
  } catch (error) {
    console.error('Failed to create WASM simulation:', error);
    return null;
  }
}

/**
 * WASM-backed simulation wrapper
 * Falls back to JS implementation if WASM not available
 */
export class WasmSimulationWrapper {
  private wasm: WasmSimulation | null = null;
  private jsFallback: import('./simulation').SimulationCanvas | null = null;
  private gridWidth: number;
  private gridHeight: number;
  private useWasm: boolean;
  
  constructor(canvas: HTMLCanvasElement, width: number, height: number, scale: number = 4) {
    this.gridWidth = width;
    this.gridHeight = height;
    
    // Try to use WASM first
    this.wasm = createWasmSimulation(width, height);
    if (this.wasm) {
      this.useWasm = true;
    } else {
      // Fall back to JS simulation
      this.useWasm = false;
      // Note: JS fallback is set up lazily when needed
      // this.jsFallback = new SimulationCanvas(canvas, width, height, scale);
    }
  }
  
  tick(): void {
    if (this.useWasm && this.wasm) {
      this.wasm.tick();
    } else if (this.jsFallback) {
      this.jsFallback.tick();
    }
  }
  
  tickMany(count: number): void {
    if (this.useWasm && this.wasm) {
      this.wasm.tick_many(count);
    } else if (this.jsFallback) {
      for (let i = 0; i < count; i++) {
        this.jsFallback.tick();
      }
    }
  }
  
  spawn(x: number, y: number, material: Material): boolean {
    if (this.useWasm && this.wasm) {
      const name = MATERIAL_NAMES[material] || 'air';
      return this.wasm.spawn(x, y, name);
    } else if (this.jsFallback) {
      return this.jsFallback.spawn(x, y, material);
    }
    return false;
  }
  
  spawnBrush(centerX: number, centerY: number, material: Material, radius: number): number {
    if (this.useWasm && this.wasm) {
      const name = MATERIAL_NAMES[material] || 'air';
      const gridX = Math.floor(centerX / 4); // Scale factor
      const gridY = Math.floor(centerY / 4);
      return this.wasm.spawn_brush(gridX, gridY, name, radius);
    } else if (this.jsFallback) {
      return this.jsFallback.spawnBrush(centerX, centerY, material, radius);
    }
    return 0;
  }
  
  clear(): void {
    if (this.useWasm && this.wasm) {
      this.wasm.clear();
    } else if (this.jsFallback) {
      this.jsFallback.clear();
    }
  }
  
  particleCount(): number {
    if (this.useWasm && this.wasm) {
      return this.wasm.particle_count();
    } else if (this.jsFallback) {
      return this.jsFallback.countParticles();
    }
    return 0;
  }
  
  getWidth(): number {
    return this.gridWidth;
  }
  
  getHeight(): number {
    return this.gridHeight;
  }
  
  /**
   * Get pixel buffer for rendering
   * Returns Uint8Array for WASM, ImageData for JS
   */
  getPixels(): Uint8Array | ImageData | null {
    if (this.useWasm && this.wasm) {
      return this.wasm.render_rgba();
    }
    return null; // JS uses canvas directly
  }
  
  /**
   * Check if using WASM backend
   */
  isUsingWasm(): boolean {
    return this.useWasm;
  }
}

/**
 * Performance metrics for WASM vs JS comparison
 */
export interface PerformanceMetrics {
  wasmTicksPerSecond: number;
  jsTicksPerSecond: number;
  wasmRenderTime: number;
  jsRenderTime: number;
  speedup: number;
}

let metricsInterval: ReturnType<typeof setInterval> | null = null;
const metrics: PerformanceMetrics = {
  wasmTicksPerSecond: 0,
  jsTicksPerSecond: 0,
  wasmRenderTime: 0,
  jsRenderTime: 0,
  speedup: 1,
};

/**
 * Start performance monitoring
 */
export function startPerformanceMonitoring(): void {
  if (metricsInterval) return;
  
  metricsInterval = setInterval(() => {
    // Update metrics periodically
    console.log('WASM Performance:', {
      ticksPerSecond: metrics.wasmTicksPerSecond,
      renderTime: metrics.wasmRenderTime,
    });
  }, 5000);
}

/**
 * Stop performance monitoring
 */
export function stopPerformanceMonitoring(): void {
  if (metricsInterval) {
    clearInterval(metricsInterval);
    metricsInterval = null;
  }
}

/**
 * Get current performance metrics
 */
export function getPerformanceMetrics(): PerformanceMetrics {
  return { ...metrics };
}